apiVersion: v1
name: code-server
version: 1.2.0
appVersion: 1.2.0
tillerVersion: ">=2.7.2"
description: Helm chart code-server
keywords:
  - code-server
sources:
  - http://github.com/0x1d/code-server
engine: gotpl
